site_name: Qiling Framework Documentation
site_description: Qiling Framework advanced binary analysis framework.
#site_favicon: 
site_url: https://qilingframework.readthedocs.org
repo_url: https://github.com/qilingframework/rtfd.io
theme: readthedocs
pages:
- 'index.md'
- 'getting_started.md'
- 'demo.md'
- 'usage.md'
- 'print.md'
- 'hijack.md'
- 'profile.md'
- 'debugger.md'
- 'register.md'
- 'memory.md'
- 'hook.md'
- 'faq.md'
