site_name: Qiling Framework Documentation
site_description: Qiling Framework advanced binary analysis framework.
site_url: https://qilingframework.rtfd.io
#repo_url: https://github.com/qilingframework/rtfd.io
theme: readthedocs
site_favicon: favicon.png
markdown_extensions:
  - attr_list
  - admonition
extra_css:
  - css/my.css

nav:
- 'Introduction': 'index.md'
- 'Installation': 'install.md'
- 'Demo': 'demo.md'
- 'Getting Started': 'howto.md'
- 'qltool': 'qltool.md'
- 'Print and Filter': 'print.md'
- 'Hijack': 'hijack.md'
- 'Snapshot': 'snapshot.md'
- 'Profile': 'profile.md'
- 'Remote debugging': 'debugger.md'
- 'CPU': 'cpu.md'
- 'Register': 'register.md'
- 'Memory': 'memory.md'
- 'Pack and Unpack': 'struct.md'
- 'Hook': 'hook.md'
- 'Qiling Debugger': 'qdb.md'
- 'Coverage': 'coverage.md'
- 'Adding Syscall and OS API': 'syscall_api.md'
- 'EVM Engine': 'evm.md'
- 'Extending Arch, OS or Loader': 'extension.md'
- 'IDAPro Plugin': 'ida.md'
- 'FAQ': 'faq.md'
- 'Checklist': 'checklist.md'
- 'Contribution Guide': 'contribution.md'
- 'References': 'references.md'
