site_name: Qiling Framework Documentation
site_description: Qiling Framework advanced binary analysis framework.
site_url: https://qilingframework.rtfd.io
#repo_url: https://github.com/qilingframework/rtfd.io
theme: readthedocs
site_favicon: favicon.png

nav:
- 'Introduction': 'index.md'
- 'Getting Started': 'getting_started.md'
- 'Demo': 'demo.md'
- 'How-to-start': 'usage.md'
- 'qltool': 'qltool.md'
- 'Print': 'print.md'
- 'Hijack': 'hijack.md'
- 'Profile': 'profile.md'
- 'Remote debugging': 'debugger.md'
- 'Register': 'register.md'
- 'Memory': 'memory.md'
- 'Pack and Unpack': 'struct.md'
- 'Hook': 'hook.md'
- 'FAQ': 'faq.md'
