site_name: Qiling Framework Documentation
site_description: Qiling Framework advanced binary analysis framework.
site_favicon: img/favico.ico 
site_url: https://qilingframework.rtfd.io
repo_url: https://github.com/qilingframework/rtfd.io
theme: readthedocs
nav:
- 'index.md'
- 'getting_started.md'
- 'demo.md'
- 'usage.md'
- 'print.md'
- 'hijack.md'
- 'profile.md'
- 'debugger.md'
- 'register.md'
- 'memory.md'
- 'struct.md'
- 'hook.md'
- 'faq.md'
