site_name: Qiling Framework Documentation
site_description: Qiling Framework advanced binary analysis framework.
site_url: https://qilingframework.rtfd.io
repo_url: https://github.com/qilingframework/rtfd.io
theme: readthedocs
site_favicon: favicon.ico

nav:
- ['index.md', 'Introduction']
- ['getting_started.md', 'Getting Started']
- ['demo.md', 'Demonstration']
- ['usage.md', 'How-to']
- ['print.md', 'Print']
- ['hijack.md', 'Hijack']
- ['profile.md', Profile']
- ['debugger.md', 'Remote debugging']
- ['register.md', 'Register']
- ['memory.md', 'Memory']
- ['struct.md', 'Struct']
- ['hook.md', 'Hook']
- ['faq.md', 'FAQ']
